name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Clean install dependencies
        run: |
          rm -rf node_modules
          rm -rf .next
          rm -rf out
          npm ci

      - name: Build
        run: |
          npm run build
          # Create necessary files for GitHub Pages
          touch ./out/.nojekyll
          echo "bikesprojects.mcdonge.github.io" > ./out/CNAME
          # Verify the build output
          ls -la ./out

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
          force_orphan: true
          commit_message: "Deploy: ${{ github.event.head_commit.message }}" 